[package]
name = "sabreur"
version = "0.1.0"
authors = ["Anicet Ebou <anicet.ebou@gmail.com>"]
edition = "2018"
exclude = ["tests/*"]
description = "sabreur is a barcode demultiplexing tool for fasta and fastq files"
homepage = "https://github.com/Ebedthan/sabreur"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["bioinformatics", "demultiplexing", "triming"] 

[dependencies]
anyhow        = "1.0.40"
bio           = "*"
clap          = "~2.33"
niffler       = "2.3"
num_cpus      = "1.13"

[dev-dependencies]
criterion = "0.3"

[profile.release]
opt-level       = 2
debug           = true
overflow-checks = false
lto             = 'thin'
panic           = 'abort'
incremental     = false

[[bin]]
name = "sabreur"
path = "src/main.rs"