[package]
name = "sabreur"
version = "0.1.0"
authors = ["Anicet Ebou <anicet.ebou@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow        = "1.0.40"
bio           = "*"
clap          = "~2.33"
chrono        = "0.4.19"
fern          = "0.5"
log           = "0.4"
niffler       = "2.3.1"
num_cpus      = "1.13.0"
relative-path = "1.3.2"
thiserror     = "1"
which         = "4.1.0"

[profile.release]
debug           = true
lto             = 'thin'
opt-level       = 3
overflow-checks = false
panic           = 'abort'
incremental     = false

[[bin]]
name = "sabreur"
path = "src/main.rs"