[package]
name = "sabreur"
version = "0.1.2"
authors = ["Anicet Ebou <anicet.ebou@gmail.com>"]
edition = "2018"
exclude = ["CODE_OF_CONDUCT.md", "tests/*", "benches/*", ".github/*"]
description = "sabreur is a barcode demultiplexing tool for fasta and fastq files"
homepage = "https://github.com/Ebedthan/sabreur"
readme = "README.md"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["bioinformatics", "demultiplexing"] 

[dependencies]
anyhow        = "1.0.40"
bio           = "0.33.0"
clap          = "~2.33"
colored       = "2"
exitcode      = "1.1.2"
human-panic   = "1.0.3"
niffler       = "2.3"

[dev-dependencies]
criterion     = "0.3"

[profile.release]
opt-level       = 3
debug           = true
overflow-checks = false
lto             = 'thin'
panic           = 'abort'
incremental     = false

[[benches]]
name = "my_benchmark"
harness = false

[[bin]]
name = "sabreur"
path = "src/main.rs"